--- 
- name: install java and tomcat
  hosts: webservers
  user: ansible
  become: yes
  connection : ssh

  tasks: 
    - name: install java s/w on redhat
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"

    - name: install java s/w on debian
      ansible.builtin.apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Download tomcat s/w
      get_url:
        url:  https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.9/bin/apache-tomcat-10.1.9.tar.gz  
        dest: /opt


    - name: extract tomcat s/w
      unarchive:
        src: /opt/apache-tomcat-10.1.9.tar.gz
        dest: /opt
        remote_src: yes

    - name: providing executable permissions
      file: 
        path: /opt/apache-tomcat-10.1.9.tar.gz/bin/startup.sh
        mode: 0777
    
    - name: start tomcat service
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-10.1.9.tar.gz/bin


