--- #
- hosts: webservers
  user: ansible
  connection: ssh
  become: yes

  tasks:
    - name: creating multiple user
      yum: name = '{{item}}' state= present
      with_items: 
            - raj
            - vicky
            - john
            - wick

